### ISSUE TITLE
Feature Request: Render to location option

### ISSUE THREAD

**Issue by STROUDICOUS** [kapoko/audio-video-merger#2]
Super useful utility - thanks

Is it possible that the outputted video is saved to the audio file location, not the video file location?

I have a bunch of audio files to be rendered to the same video all in different sub-folders. Re-uniting the video file to the audio file's location can be laborious, but I suspect this could be easily remedied? 

Thanks

**Comment by kapoko** [comment]
Thanks for the suggestion, I think this would indeed be more logical behavior. 

Just released [1.1.0](https://github.com/kapoko/audio-video-merger/releases/tag/v1.1.0) which defaults this (2048cbf), you can download the latest version [here](https://audiovideomerger.github.io).

**Comment by STROUDICOUS** [comment]
Good lawd that was fast implementation. Thank you! Works like a dream
